<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HsePelaporanBahayaSeeder extends Seeder
{
    /**
     * Seed the thsepelaporanbahaya table with sample data.
     *
     * Foreign key references (thsedata_master):
     *   shift          : 1 = Pagi, 2 = Malam
     *   kategori_bahaya: 3 = Kondisi Tidak Aman, 4 = Tindakan Tidak Aman
     *   status_pelaporan: 5 = Open, 6 = On Progress, 7 = Closed
     *   data_pelaporan  : 8 = Inspection, 9 = Hazard report
     */
    public function run(): void
    {
        $data = [
            [
                'tgl_pelaporan'      => '2026-07-01',
                'lokasi_bahaya'      => 'Area Workshop A',
                'shift'              => 1,
                'data_pelaporan'     => 8,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Terdapat tumpahan oli di lantai area mesin bubut',
                'desc_temuan_bahaya' => 'Karyawan berpotensi terpeleset saat melintasi area tersebut',
                'rekomendasi_perbaikan' => 'Segera membersihkan tumpahan oli dan memasang rambu peringatan',
                'dept_penanggungjwb' => 'Maintenance',
                'nama_pengawas'      => 'Budi Santoso',
                'due_date'           => '2026-07-03',
                'status_pelaporan'   => 7,
                'created_date'       => '2026-07-01 07:30:00',
                'created_by'         => '002809',
                'updated_date'       => '2026-07-03 09:00:00',
                'updated_by'         => '002809',
            ],
            [
                'tgl_pelaporan'      => '2026-07-01',
                'lokasi_bahaya'      => 'Area Stock Yard',
                'shift'              => 2,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 4,
                'desc_kategori_bahaya' => 'Operator crane tidak menggunakan sabuk pengaman saat mengoperasikan crane',
                'desc_temuan_bahaya' => 'Melanggar prosedur K3 dan berisiko jatuh dari ketinggian',
                'rekomendasi_perbaikan' => 'Memberikan peringatan tertulis dan mewajibkan penggunaan safety harness',
                'dept_penanggungjwb' => 'HSE',
                'nama_pengawas'      => 'Agus Wijaya',
                'due_date'           => '2026-07-02',
                'status_pelaporan'   => 7,
                'created_date'       => '2026-07-01 15:45:00',
                'created_by'         => '001005',
                'updated_date'       => '2026-07-02 10:30:00',
                'updated_by'         => '001005',
            ],
            [
                'tgl_pelaporan'      => '2026-07-03',
                'lokasi_bahaya'      => 'Area Office Lt.2',
                'shift'              => 1,
                'data_pelaporan'     => 8,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Kabel stop kontak terkelupas dan terbuka di ruang rapat',
                'desc_temuan_bahaya' => 'Risiko tersengat listrik saat karyawan menyentuh area tersebut',
                'rekomendasi_perbaikan' => 'Mengganti kabel dan stop kontak, serta melakukan pengecekan instalasi listrik',
                'dept_penanggungjwb' => 'General Affair',
                'nama_pengawas'      => 'Dewi Sartika',
                'due_date'           => '2026-07-05',
                'status_pelaporan'   => 6,
                'created_date'       => '2026-07-03 08:15:00',
                'created_by'         => '003012',
                'updated_date'       => '2026-07-04 11:00:00',
                'updated_by'         => '003012',
            ],
            [
                'tgl_pelaporan'      => '2026-07-04',
                'lokasi_bahaya'      => 'Area Workshop B',
                'shift'              => 1,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Alat pemadam api ringan (APAR) tidak terisi dan melewati masa uji',
                'desc_temuan_bahaya' => 'Tidak siap digunakan jika terjadi kebakaran darurat',
                'rekomendasi_perbaikan' => 'Melakukan pengisian ulang APAR dan menjadwalkan uji kelayakan rutin',
                'dept_penanggungjwb' => 'HSE',
                'nama_pengawas'      => 'Budi Santoso',
                'due_date'           => '2026-07-07',
                'status_pelaporan'   => 6,
                'created_date'       => '2026-07-04 09:30:00',
                'created_by'         => '002809',
                'updated_date'       => '2026-07-05 08:00:00',
                'updated_by'         => '002809',
            ],
            [
                'tgl_pelaporan'      => '2026-07-05',
                'lokasi_bahaya'      => 'Area Parkir Mobile Crane',
                'shift'              => 2,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 4,
                'desc_kategori_bahaya' => 'Riggers tidak menggunakan helm dan rompi safety saat melakukan bongkar muat',
                'desc_temuan_bahaya' => 'Berisiko cedera kepala jika tertimpa material',
                'rekomendasi_perbaikan' => 'Teguran lisan dan pengawasan ketat penggunaan APD oleh supervisor',
                'dept_penanggungjwb' => 'Operasional',
                'nama_pengawas'      => 'Hendra Gunawan',
                'due_date'           => '2026-07-05',
                'status_pelaporan'   => 7,
                'created_date'       => '2026-07-05 14:00:00',
                'created_by'         => '004021',
                'updated_date'       => '2026-07-05 16:30:00',
                'updated_by'         => '004021',
            ],
            [
                'tgl_pelaporan'      => '2026-07-06',
                'lokasi_bahaya'      => 'Area Gudang Sparepart',
                'shift'              => 1,
                'data_pelaporan'     => 8,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Rak penyimpanan sparepart miring dan tidak stabil',
                'desc_temuan_bahaya' => 'Sparepart berat berpotensi jatuh dan melukai karyawan',
                'rekomendasi_perbaikan' => 'Memperbaiki rak dan memastikan semua baut terpasang dengan benar',
                'dept_penanggungjwb' => 'Warehouse',
                'nama_pengawas'      => 'Slamet Riyadi',
                'due_date'           => '2026-07-08',
                'status_pelaporan'   => 5,
                'created_date'       => '2026-07-06 10:00:00',
                'created_by'         => '005017',
                'updated_date'       => null,
                'updated_by'         => null,
            ],
            [
                'tgl_pelaporan'      => '2026-07-06',
                'lokasi_bahaya'      => 'Area Fuel Station',
                'shift'              => 2,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Terdapat ceceran solar di sekitar dispensing area',
                'desc_temuan_bahaya' => 'Area licin dan berisiko kebakaran jika terkena percikan api',
                'rekomendasi_perbaikan' => 'Membersihkan ceceran solar dan menyediakan spill kit di area fueling',
                'dept_penanggungjwb' => 'HSE',
                'nama_pengawas'      => 'Agus Wijaya',
                'due_date'           => '2026-07-07',
                'status_pelaporan'   => 5,
                'created_date'       => '2026-07-06 17:15:00',
                'created_by'         => '002809',
                'updated_date'       => null,
                'updated_by'         => null,
            ],
            [
                'tgl_pelaporan'      => '2026-07-07',
                'lokasi_bahaya'      => 'Area Workshop A',
                'shift'              => 1,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 4,
                'desc_kategori_bahaya' => 'Pekerja las tidak menggunakan kacamata pelindung saat mengelas',
                'desc_temuan_bahaya' => 'Paparan sinar las dapat merusak mata dalam jangka pendek maupun panjang',
                'rekomendasi_perbaikan' => 'Menyediakan dan mewajibkan penggunaan welding mask yang layak',
                'dept_penanggungjwb' => 'Produksi',
                'nama_pengawas'      => 'Supriyadi',
                'due_date'           => '2026-07-08',
                'status_pelaporan'   => 5,
                'created_date'       => '2026-07-07 08:30:00',
                'created_by'         => '003012',
                'updated_date'       => null,
                'updated_by'         => null,
            ],
            [
                'tgl_pelaporan'      => '2026-07-07',
                'lokasi_bahaya'      => 'Area Kantin',
                'shift'              => 1,
                'data_pelaporan'     => 8,
                'kategori_bahaya'    => 3,
                'desc_kategori_bahaya' => 'Lantai kantin licin akibat tumpahan minyak dan tidak ada tanda peringatan',
                'desc_temuan_bahaya' => 'Karyawan berpotensi terpeleset saat jam istirahat',
                'rekomendasi_perbaikan' => 'Memasang rambu peringatan dan membersihkan lantai secara berkala',
                'dept_penanggungjwb' => 'General Affair',
                'nama_pengawas'      => 'Dewi Sartika',
                'due_date'           => '2026-07-08',
                'status_pelaporan'   => 5,
                'created_date'       => '2026-07-07 12:00:00',
                'created_by'         => '001005',
                'updated_date'       => null,
                'updated_by'         => null,
            ],
            [
                'tgl_pelaporan'      => '2026-07-08',
                'lokasi_bahaya'      => 'Area Stock Yard',
                'shift'              => 2,
                'data_pelaporan'     => 9,
                'kategori_bahaya'    => 4,
                'desc_kategori_bahaya' => 'Sling wire rope sudah aus dan tidak layak pakai digunakan untuk mengangkat beban',
                'desc_temuan_bahaya' => 'Risiko sling putus dan beban jatuh yang dapat menyebabkan kecelakaan fatal',
                'rekomendasi_perbaikan' => 'Mengganti wire rope dengan yang baru dan melakukan inspeksi rutin',
                'dept_penanggungjwb' => 'Operasional',
                'nama_pengawas'      => 'Hendra Gunawan',
                'due_date'           => '2026-07-10',
                'status_pelaporan'   => 5,
                'created_date'       => '2026-07-08 07:00:00',
                'created_by'         => '004021',
                'updated_date'       => null,
                'updated_by'         => null,
            ],
        ];

        // Hapus data existing dulu agar bisa di-re-run dengan aman
        DB::table('thsepelaporanbahaya')->truncate();
        DB::table('thsepelaporanbahaya')->insert($data);
    }
}
